import = ["/Users/guidooffermans/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[mouse]
# hide_when_typing = true

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.8
startup_mode = "Windowed"

[window.padding]
x = 10
y = 10

[shell]
program = "/bin/zsh"