import = ["/Users/guidooffermans/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 17.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[mouse]
# hide_when_typing = true

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.8
startup_mode = "Windowed"
option_as_alt ="both"

[window.padding]
x = 10
y = 10

[shell]
program = "/bin/zsh"

[keyboard]
bindings = [
    { key = "H", mods = "Alt", chars = "h" },
    { key = "J", mods = "Alt", chars = "j" },
    { key = "K", mods = "Alt", chars = "k" },
    { key = "L", mods = "Alt", chars = "x1bL" },
]
